#!/usr/bin/env python3
"""原子避坑知识资产生成器：条目定义即数据，跑一次刷新全部条目文件+INDEX。
新增条目只改 ITEMS 列表。字段：id/cat/title/symptom/cause/rule/src/verify
"""

import os

ITEMS = [
    # ── wayland ──────────────────────────────────────────────────────────
    dict(id="wl-listener-data-slot", cat="wayland",
         title="libwayland listener data 与 proxy user_data 同槽",
         symptom="surface enter 回调拿到的 this 是零块/野指针，SEGV 于 map 遍历",
         cause="wl_proxy_add_listener 的 data 与 wl_proxy_set_user_data 共用同一槽；先挂 listener 再 set_user_data 会覆盖",
         rule="需要两者共存时：listener data 指向自建块，块头部存 this 反向指针（compat calloc 方案）；或不用 set_user_data",
         src="popup_surface.cpp surfaceEnter 注释；2026-08-25 多输出重构 SEGV 定案",
         verify="容器双 scale 套件 + 指针进 popup 不崩用例"),
    dict(id="wl-input-popup-single-slot", cat="wayland",
         title="smithay input popup 单槽 last-create-wins",
         symptom="上屏后卡片停在旧光标；classicui 打拼音后我们不再被重定位",
         cause="每条 zwp_input_method_v2 连接只追踪最后创建的 get_input_popup_surface；光标矩形事件只发槽内者",
         rule="show 每次重建 popup（重夺槽+继承 handle 保留的最新矩形）；hide 先 attach(null)+commit 再 destroy（且防残影）",
         src="实验 007；c7/c8 抢槽用例",
         verify="c8-refollow-gtk：hide 销毁×2 + 重建×1"),
    dict(id="wl-per-surface-state-rebuild", cat="wayland",
         title="per-surface 状态必须随 surface 重建全量重放",
         symptom="切应用后卡片放大 scale 倍/鼠标失灵/点不进",
         cause="viewport destination、fractional 监听、input region 都是 per-surface 的；重建后依赖『首次流程设过』必失效",
         rule="surface 重建路径全量重放 show 的全部 surface 级副作用（destination/input region/可见帧）",
         src="experiment-007 教训条；viewport destination 修复（切应用放大+鼠标灭）",
         verify="c5/c6 交互闭环"),
    dict(id="wl-state-atomic-with-buffer", cat="wayland",
         title="表面状态变更须与承载 buffer 原子成对",
         symptom="resize/移动时卡片跳闪 1-2 帧（旧 buffer 被拉伸）",
         cause="急切改 viewport destination 而新尺寸 buffer 下一帧才 commit",
         rule="destination 只与匹配尺寸 buffer 同一 commit 下发（syncViewport 统一收口全部 commit 点）",
         src="fix/resize-flicker",
         verify="录像逐帧 vision 复核"),
    dict(id="wl-empty-input-region", cat="wayland",
         title="隐藏态必须显式清空输入区",
         symptom="透明卡片区域挡住下方应用按钮",
         cause="layer surface 输入区与像素透明度无关，不显式清空则『出现过的区域』全程可命中",
         rule="创建即挂空 region；show 恢复全量（nullptr）；show 之后的 surface 交换也要重放恢复",
         src="r22 穿透用例；fallback 鼠标失灵修复",
         verify="c6 隐藏后穿透断言"),
    dict(id="wl-surface-listener-v5-slots", cat="wayland",
         title="wl_surface listener v5 槽位不能留 NULL",
         symptom="分数 scale 下合成器发 preferred_buffer_scale 即 abort",
         cause="listener 函数指针槽为 NULL 时 libwayland 直接 abort（协议版本升档新增事件）",
         rule="listener 结构体全部槽位显式填（哪怕空 lambda）；wl_seat name 同理",
         src="2026-08-25 多输出版崩溃",
         verify="NIRI_TEST_SCALE=1.5/2.0 全套件"),
    dict(id="wl-pointer-set-cursor", cat="wayland",
         title="pointer enter 后必须 set_cursor",
         symptom="鼠标移到卡片上指针消失",
         cause="Wayland 协议要求客户端在 enter 后主动设置光标，否则合成器隐藏",
         rule="seat capabilities 得指针后进 enter 时 set_cursor（cursor-shape-v1 set_shape DEFAULT）",
         src="宿主机『卡上无鼠标指针』修复",
         verify="surface-test 场景人工/截图"),
    dict(id="wl-fractional-last-known", cat="wayland",
         title="新 surface fractional 未到时用上次值兜底",
         symptom="重启后第二个应用起卡片放大 2x",
         cause="layer surface 无 fractional 事件时落到 wl_output 整数 scale（ceil=2）",
         rule="缓存 lastFscaleNum_，新 surface 事件未到时优先于整数兜底",
         src="多屏混 scale 修复 b3ff816",
         verify="多输出/切应用场景"),
    dict(id="wl-scale-from-zxdg-output", cat="wayland",
         title="精确 scale 用 zxdg-output 推导",
         symptom="分数 scale 下缓冲与窗口比例错、卡片等比缩水",
         cause="wl_output 整数 scale 与真实分数 scale 不符",
         rule="scale()=zxdg logical_size ÷ wl_output mode 物理尺寸；绑定全部输出+surface enter 跟踪所在屏",
         src="染色法破案（6525f63）+ 多输出重构（3b48ddb）",
         verify="容器真 1.5/2.0 双绿"),
    dict(id="wl-preedit-needs-updatepreedit", cat="wayland",
         title="client preedit 必须经 updatePreedit() 送达应用",
         symptom="设了 preedit 应用毫无反应",
         cause="updateUserInterface 只刷 UI 插件，不产生 UpdatePreeditEvent→waylandim→应用链路",
         rule="推组合文本必须 ic->updatePreedit()；探针/内联预览全靠它",
         src="可见组合文本实时跟随定案",
         verify="c9 探针+矩形事件断言"),
    dict(id="wl-rect-latency-unbounded", cat="wayland",
         title="光标矩形延迟无上界，禁用固定截止窗",
         symptom="首应用跟随、第二个应用起误回退底部（或反之）",
         cause="『应用不报矩形』与『矩形迟到』用短窗口区分不开；1500ms 复测仍不稳",
         rule="无截止时限：判定挂起 decisionPending_，矩形到或录音结束才结算 layer；8s 保险丝只兜异常",
         src="experiment-007 首聚 saga 三连翻案",
         verify="c10 跨应用首聚"),
    dict(id="wl-chromium-rect-only-on-change", cat="wayland",
         title="chromium 系只在文本/光标变化时报矩形",
         symptom="焦点时零矩形事件，看似不支持跟随",
         cause="chromium 不在焦点时报 text_input_rectangle，只在上屏插入/拼音组合时报",
         rule="动态判断：prepare 建 popup 探测、show 仍无非零矩形→回退；上屏记账 committedInThisIC_ 下轮继承",
         src="r24/r26 定案",
         verify="c7 chromium 三幕幕 2"),
    dict(id="wl-niri-popup-no-clamp", cat="wayland",
         title="niri 不替 input popup 滑位/钳制",
         symptom="光标下方放不下时卡片出屏不可见",
         cause="niri 的 popup 定位不做越界滑动（ConstraintAdjustment 不生效于该路径）",
         rule="自己翻转/钳制：下方放不下翻上方，再钳入可见区",
         src="ghostty 末行出屏修复链",
         verify="surface-test 末行场景"),
    # ── x11 / satellite ──────────────────────────────────────────────────
    dict(id="x-cw-valueorder", cat="x11",
         title="xcb CreateWindow 值列表必须按 CW 位序",
         symptom="BadValue、窗口从未创建（创建日志是请求后乐观打印）",
         cause="value 数组按 mask 位序解包；顺序写反=把事件掩码大整数当布尔读",
         rule="严格按 border_pixel<save_under<override_redirect<event_mask<colormap 顺序；独立小程序先证再移植",
         src="0.3.0.36 总根源破案（/tmp/xorder.c）",
         verify="X OR 卡片窗创建日志 + 零 X 错误"),
    dict(id="x-error-events-not-silent", cat="x11",
         title="X 错误事件不能静默吞",
         symptom="『完全没效果』类问题无任何日志线索",
         cause="response_type==0 的错误事件被直接 free",
         rule="错误事件限流打日志（code+seq）；BadValue/BadGC/BadDrawable 一眼定位",
         src="0.3.0.35 加 [x11diag] 日志",
         verify="journal 无 X 错误即健康"),
    dict(id="x-gc-per-window", cat="x11",
         title="GC 必须随窗口销毁重建",
         symptom="窗重建后 put_image 全败（BadGC）",
         cause="GC 绑定 drawable，窗口销毁后 GC 悬空",
         rule="每个新窗口配新 GC；销毁时同时 xcb_free_gc",
         src="0.3.0.35 透明窗破案",
         verify="同上"),
    dict(id="x-argb32-visual", cat="x11",
         title="32 位 ARGB visual + colormap 才有透明",
         symptom="卡片四周阴影/圆角渲染成黑边",
         cause="24 位深度无 alpha 通道",
         rule="枚举 depth-32 TrueColor visual 建独立 colormap；无则退化 root_visual 带黑边兜底",
         src="0.3.0.37（/tmp/xargb.c 先证）",
         verify="透明区透出桌面非黑"),
    dict(id="x-satellite-root-origin", cat="x11",
         title="satellite 把所有顶层 X 窗摆在根 (0,0)",
         symptom="X 应用的 mapToGlobal 是窗口局部物理值，右列窗口矩形整体偏左",
         cause="xwayland-satellite 无 WM 布局，顶层窗根坐标恒 (0,0)；真实原点由 OR 窗父子化时合成器叠加",
         rule="X 应用 dbus 矩形按『窗口局部=X 根坐标』理解；卡片走 X OR 窗让 satellite 挂靠叠加原点",
         src="右列错位根因定案（query tree 实测）",
         verify="c5 贴光标 + WPS 左右列"),
    dict(id="x-satellite-parent-bounds", cat="x11",
         title="OR 卡片必须钳入聚焦 X 顶层窗范围",
         symptom="卡片映成独立顶层窗→niri 平铺到别处/抢键盘焦点→会话卡死",
         cause="卡片越出父窗（或 X 屏）时 satellite 拒绝父子化走独立窗回退",
         rule="queryFocusGeometryLocked 实时取父窗尺寸，先翻上方再钳窗界；X 屏只兜底（高浮动窗可超屏且弹层随窗滚动）",
         src="0.3.0.39 截图对账→0.3.0.40 修正",
         verify="e2e x3-xwayland-flip"),
    dict(id="ct-satellite-nested-container", cat="container-test",
         title="xwayland-satellite 可挂嵌套合成器链（容器 X 仿真）",
         symptom="（非坑，是可行性定案）X 路径（历史 8 类 bug）此前只能宿主机验证",
         cause="sway(headless)→niri 嵌套→satellite 作为 niri 的 wayland 客户端→X app 全链可用：_NET_ACTIVE_WINDOW 判据/父窗几何/XShm/ARGB 全真实工作",
         rule="start-niri.sh 在 niri socket 就绪后启 satellite，轮询 /tmp/.X11-unix 出 socket 再 export DISPLAY（须在 start_fcitx5 前——xcb 模块要吃到）；GDK_BACKEND=x11 GTK_IM_MODULE=fcitx 跑 testapp 即 WPS 同型拓扑",
         src="feat/xwayland-test 冒烟一轮通过（2026-08-27）",
         verify="e2e X 组 x1-x5"),
    dict(id="fc-kwin-im-v1-only-pool-gate", cat="fcitx-api",
         title="嵌套 kwin 只有 input-method v1——shm 池门控被卡死",
         symptom="kde 环境 popup 永远 not ready（s2/c8-c11/x 组全灭），journal 无 shm pool ready",
         cause="popup 自建连接用 zwp_input_method_manager_v2 global 作'IM 连接'判据并门控 shm 池建立；kwin 只广播 v1（wayland-info 实测），池永不建",
         rule="池门控只看 compositor+shm；v1 合成器上 input-popup 是 v2 特性，ensurePopup 取不到 IM proxy 自然降级 layer——能力判定放使用处不放池建立处",
         src="feat/test-scenarios-complete kde 三轮定位（2026-08-27）",
         verify="gate kde 26/26"),
    dict(id="wl-mutter-rect-storm", cat="wayland",
         title="mutter 每帧重发同值 text_input_rectangle（矩形风暴）",
         symptom="gnome 全程 12.6 万条 rect 日志（~300/s），事件循环被拖死、D-Bus 触发调用超时",
         cause="mutter 对 input popup surface 逐帧重发相同矩形；addon 逐条处理+记日志",
         rule="popupRectangle 同值去重（零处理）；去重状态必须随 popup 重建重置——合成器对新 popup 重发同值矩形，不复位则首个事件被吞、hasCursorRect_/sawRealRect_ 永不置位",
         src="feat/test-scenarios-complete gnome c7/c10 排障（2026-08-27）",
         verify="gate gnome 26/26，rect 日志 12.6万→3 条"),
    dict(id="ct-grep-q-sigpipe", cat="container-test",
         title="printf|grep -q 早退撞 SIGPIPE——pipefail 下大窗口恒假败",
         symptom="断言四条件全在日志里、用例仍红（gnome 28MB journal 时）",
         cause="grep -q 首个匹配即退出，printf 继续写被 SIGPIPE；set -o pipefail 把整条管线判非零",
         rule='grep PATTERN <<<"$var" 替代 printf|grep 管线（无管道无此雷）；凡 pipefail 套件禁用 |grep -q 组合',
         src="gnome c14 两轮假败定位（2026-08-27），67 处全量替换",
         verify="三环境 gate 全绿"),
    dict(id="ct-bash-or-and-precedence", cat="container-test",
         title="bash {A&&B||C&&D} 左结合拆散双档断言",
         symptom="双档条件（popup 环境||layer 环境）在第一档为真的环境里反而判负",
         cause="&& 与 || 同优先级左结合：(A&&B)||C 再 &&D——D 属于第二档却对第一档结果生效",
         rule="多档断言显式分组 {{一档;} || {二档;}；写完用双环境值各单测一次条件表达式",
         src="gnome c9 rebuild=2 rect=7 仍红的离谱现场（2026-08-27）",
         verify="IS_POPUP_ENV 1/0 双值单测通过"),
    dict(id="ct-env-capability-matrix", cat="container-test",
         title="合成器能力矩阵：popup 与指针注入是两个独立维度",
         symptom="同是'非 niri'环境，断言分档错位（gnome 有 popup 无指针；kwin 两者皆无）",
         cause="input-method-v2：niri✓ mutter✓ kwin✗(仅 v1)；wlr-virtual-pointer：niri✓ kwin✗ mutter 有协议但嵌套无头不投递（点击零焦点变化实证）",
         rule="IS_POPUP_ENV（kde 排除）与 IS_POINTER_ENV（仅 niri）独立判定；wayland-info 实测为准，协议在≠投递通；mutter 无头还有窗口焦点漂移+chromium 偶发 crashpad，用例需触发重试与崩溃感知档",
         src="feat/test-scenarios-complete wayland-info 双环境探测（2026-08-27）",
         verify="三环境 26/26 各走各档"),
    dict(id="ct-case-config-leak", cat="container-test",
         title="用例改配置必须还原到产品默认（不是任意安全值）",
         symptom="X 组单跑全绿、全量跑全灭（X 分支整组静默关闭走 overlay 兜底）",
         cause="c5 尾部把 DbusPosition 还原成 bottom——那是旧默认值；产品默认已改 follow，泄漏让 c5 之后所有依赖 follow 的用例静默变行为",
         rule="用例内 set_cfg 的还原值抄产品默认（config 头里的 default），不许凭记忆写'安全值'；对配置敏感的用例组开头防御性自设基线（X 组自设 follow）；新用例组单跑绿+全量跑绿都过了才算绿",
         src="feat/xwayland-test 全量门禁 21/26 两轮定位（2026-08-27）",
         verify="gate-merge 26/26×2"),
    dict(id="x-satellite-or-no-pointer", cat="x11",
         title="satellite 0.8.2 不向 override-redirect 窗投递指针事件",
         symptom="X 卡片可见（合成正常）但 hover 永不触发；独立最小 OR 探针窗同样零事件（甚至不被合成）",
         cause="satellite 对 OR 窗的 wayland popup 不转发 wl_pointer（上游已知 X11 弹窗限制；niri 文档明示）",
         rule="X 卡交互断言走键盘路径（数字键/回车）；指针链留 'X 指针 enter' 日志作能力探测，卫星修复后用例自动升级；宿主机 WPS 卡 hover 同样不可用属上游限制，勿在 addon 侧修",
         src="x6 两轮最小探针复现（2026-08-27，satellite 0.8.2-1）",
         verify="e2e x6-xwayland-pointer"),
    dict(id="x-satellite-screen-model", cat="x11",
         title="satellite X 屏=逻辑原点+物理范围",
         symptom="多输出下 X 坐标与 wayland 逻辑布局对不上",
         cause="X root 尺寸=输出按逻辑原点摆放、范围取物理尺寸（宿主 4672×1512）",
         rule="输出 X 区段判定用 logicalX/Y+physW/H；root 尺寸连接时记录",
         src="宿主实测定案",
         verify="X 区段钳制用例"),
    dict(id="x-active-window-classifier", cat="x11",
         title="_NET_ACTIVE_WINDOW 存在⟺聚焦应用是 X 应用",
         symptom="program/WM_CLASS 判 X 应用恒失败（program 恒空）",
         cause="satellite 在 wayland 应用聚焦时清空该属性；DBus IC 的 program() 首次 FocusIn 乃至整个会话可为空",
         rule="rectIsXPhysical（矩形超全部输出逻辑范围）|| 活动窗存在，任一命中即 X 路径；负结果不缓存（清除有时序竞态）",
         src="0.3.0.33 判据演化",
         verify="X OR 模式进入日志"),
    dict(id="x-gtk-scrolled-doc-coords", cat="x11",
         title="GTK 滚动文档坐标虚报",
         symptom="末行输入时光标矩形 y 超窗口高（如 1080 高的窗报 2250）",
         cause="GtkTextView 内层控件 allocation 是全文档高度，非视口",
         rule="矩形超窗高按虚报处理（翻转+钳制兜住）；勿拿它当光标真值",
         src="ghostty/gte 末行 rect 对账",
         verify="surface-test 长文档场景"),
    dict(id="x-xshm-works", cat="x11",
         title="MIT-SHM 在 satellite 下可用",
         symptom="-",
         cause="Xwayland 共享内存扩展 v1.2 shared_pixmaps=1 可用",
         rule="帧传输用 XShm PutImage 即可，无需回退纯 PutImage",
         src="/tmp/xshmcard.c 实证",
         verify="X 卡片帧到达"),
    # ── fcitx5 API ───────────────────────────────────────────────────────
    dict(id="fc-xcb-interface-target", cat="fcitx-api",
         title="Fcitx5::Module::XCB 是 INTERFACE 目标",
         symptom="宿主首调即 symbol lookup error 崩溃，容器测不出",
         cause="该 CMake 目标只给头文件；libxcb/libxcb-shm 必须 pkg_check_modules 显式链",
         rule="链接xfcitx 模块依赖后必做 readelf -d 检查 + smoke 加 ldd -r 拦截",
         src="0.3.0.27 崩机教训",
         verify="smoke.sh ldd -r"),
    dict(id="fc-setconfig-string-values", cat="fcitx-api",
         title="D-Bus SetConfig 的值必须是字符串",
         symptom="int32 值被静默丢弃，落盘成默认值",
         cause="Controller1 配置接口值类型全为 s（GetConfig 回读全带引号）",
         rule="gdbus 传 <'10'> 而非 <10>",
         src="r36 首跑失败定案",
         verify="GetConfig 回读对账"),
    dict(id="fc-config-section-append", cat="fcitx-api",
         title="配置文件追加键不能落进节内",
         symptom="追加的配置项静默失效",
         cause="ini 末尾若残留 [节]，追加行被解析成节键",
         rule="程序化改配置先检查节边界；用 SetConfig 而非 echo >>",
         src="WPS 首测未跟随的全部原因",
         verify="configtool 回读"),
    dict(id="fc-setconfig-override", cat="fcitx-api",
         title="addon 必须实现 setConfig 覆写",
         symptom="configtool 点保存毫无效果",
         cause="基类 setConfig 默认 no-op",
         rule="实现 load+migrate+save+应用（热生效项如字体/定位策略在 setConfig 内处理）",
         src="aiinput setConfig 实现",
         verify="s4 顺带覆盖"),
    dict(id="fc-addon-reload-remote-r", cat="fcitx-api",
         title="容器里 fcitx5-remote -r 不触发 addon reloadConfig",
         symptom="改文件+remote -r 后配置未生效",
         cause="该路径只重载部分配置（容器实测 addon 无 config-reloaded 日志）",
         rule="测试改配置走 SetConfig（字符串值）；文件直改须重启 fcitx5",
         src="r36 调查",
         verify="config-reloaded 日志"),
    dict(id="fc-input-popup-api", cat="fcitx-api",
         title="getInputMethodV2 仅对 wayland_v2 IC 非空",
         symptom="DBus 前端 IC 拿不到 IM proxy，input popup 路径不可达",
         cause="waylandim 公开 API 动态_cast wayland_v2 前端 IC；dbus IC 无 IM 连接侧身份",
         rule="imAvailable 判定驱动：无 proxy→overlay/X 路径；这也是 classicui 对 dbus IC 的同款行为",
         src="classicui 源码核读 + 实验实验 008",
         verify="c5 overlay 日志"),
    dict(id="fc-classicui-dispatch", cat="fcitx-api",
         title="classicui 对 dbus+wayland IC 强制 X11 UI（上游自认位置错）",
         symptom="以为 classicui 对 gte 类应用有精确定位手段",
         cause="classicui.cpp update() 路由 dbus IC 到 X11 UI；xcbinputwindow 无坐标翻译；上游注释原话 position will be wrong anyway",
         rule="对标 classicui 时按前端分流：wayland_v2=合成器 popup 精确；dbus=同样拿不到窗口原点（我们 overlay/X 路径已是同类最优）",
         src="实验 008 定案",
         verify="surface-test 并排对比"),
    dict(id="fc-timer-usec", cat="fcitx-api",
         title="addTimeEvent 用绝对 µs + setOneShot",
         symptom="定时器不触发或语义混乱",
         cause="sd-event 语义为绝对时间；interval 参数位是 accuracy",
         rule="nowUs()+delay 形式；一次性事件补 setOneShot()",
         src="armRecordingWatchdog 实现",
         verify="c3 看门狗"),
    dict(id="fc-uieventloop-include", cat="fcitx-api",
         title="EventLoop 完整定义在 event.h",
         symptom="编译报不完整类型",
         cause="eventloopinterface.h 只有抽象接口",
         rule="#include <fcitx-utils/event.h>",
         src="r31 开发记录",
         verify="编译"),
    # ── flutter embedder ────────────────────────────────────────────────
    dict(id="em-pointer-physical-space", cat="embedder",
         title="FlutterPointerEvent 坐标必须是物理像素",
         symptom="指针命中位置缩到左上 1/scale（悬停错行/点击失灵）",
         cause="embedder 约定 pointer 事件与 metrics 同空间（物理）；引擎内部 ÷dpr 做命中",
         rule="onPointer 前乘 metrics dpr（引擎侧缓存 lastRatio_，与 metrics 同空间无竞态）",
         src="悬停偏移真根因收口（0.3.0.23）",
         verify="c6 hover/点击"),
    dict(id="em-jit-only", cat="embedder",
         title="官方 embedder 只有 JIT 变体",
         symptom="想要 AOT",
         cause="linux-x64-embedder.zip 只出 JIT 工件",
         rule="kernel_blob + icudtl.dat 路线；无 AOT snapshot 字段",
         src="fetch-flutter-embedder.sh 注释",
         verify="构建产物清单"),
    dict(id="em-engine-hash-sdk-coupling", cat="embedder",
         title="引擎 .so 必须与构建 kernel 的 SDK 同 hash",
         symptom="运行时引擎握手失败/渲染异常",
         cause="libflutter_engine.so 按 engine hash 发布；kernel_blob 必须同 SDK 产出",
         rule="fetch 脚本从 SDK 的 engine-dart-sdk.stamp 取 hash；容器化后固定取镜像内 pin 版 SDK 的 stamp",
         src="fetch-flutter-embedder.sh",
         verify="引擎启动日志"),
    dict(id="em-window-natural-intrinsic", cat="embedder",
         title="窗口尺寸=内在尺寸+持久帧回调（勿回测量路）",
         symptom="TextPainter 预测量+补偿系数方案被用户否定",
         cause="任何字体都不该超出；测量路是死胡同",
         rule="OverflowBox 无界约束自然布局+持久帧回调回读实际渲染尺寸（量化上报）+池容量桶；UI 尺寸架构定论勿回头",
         src="用户明确定论",
         verify="UI 套件+golden"),
    dict(id="em-metrics-dpr-cache", cat="embedder",
         title="updateMetrics 时缓存 dpr 供 pointer 换算",
         symptom="与 popup scale 查询产生竞态错比",
         cause="metrics dpr 与表面 scale 到达时序不同",
         rule="dpr 只记 metrics 侧（lastRatio_），pointer 用它换算",
         src="同 pointer-physical-space",
         verify="双 scale 套件"),
    # ── 应用行为 ─────────────────────────────────────────────────────────
    dict(id="app-dbus-rect-window-local", cat="app-behavior",
         title="DBus 前端矩形=窗口局部（原点结构性缺失）",
         symptom="右列/浮动窗口卡片整体偏左",
         cause="GTK/Qt 经 dbus 报的 cursorRect 不含窗口原点；Wayland 不暴露他窗位置",
         rule="铺满输出/左列时 rect≈输出坐标（准）；半宽列 best effort 或走环境层 text-input 正解",
         src="gte 截图对账破案",
         verify="c5 maximize 场景"),
    dict(id="app-gtk-commit-no-rect-rereport", cat="app-behavior",
         title="程序性 commit 不触发矩形重报",
         symptom="卡片『迟一步』停在上一段插入点",
         cause="应用只在光标移动/文本变化时重报",
         rule="上屏后注入 Left+Right 无净位移键对（postEvent+forwardKey）逼重报",
         src="r28 三轮听写对齐",
         verify="c11 微移注入×3"),
    dict(id="app-textinput-compositor-positioned", cat="app-behavior",
         title="wayland 原生应用走 text-input 才有合成器级精确定位",
         symptom="GTK_IM_MODULE=fcitx 全局设置下 wayland 应用全走 dbus（拿不到原点）",
         cause="text-input-v3 → wayland_v2 IC → input popup 由合成器定位（右列/浮动/多输出全对）",
         rule="环境层正解：去掉全局 IM_MODULE（X 应用回落 XIM 仍可）；单应用可 GDK_BACKEND=x11 进 X 精确路径",
         src="实验 008 结论",
         verify="surface-test 对照"),
    dict(id="app-qt-dbus-needs-machineid", cat="app-behavior",
         title="Qt 的 QDBusConnection 需要 /etc/machine-id",
         symptom="Qt 应用启动即 abort（容器）",
         cause="QtDBus 缺 machine-id 直接崩",
         rule="run 脚本补写 /etc/machine-id",
         src="r34 教训",
         verify="c5 testapp-qt"),
    dict(id="fc-dbus-im-protocol-paths", cat="fcitx-api",
         title="dbus 前端 IM 协议路径与接口",
         symptom="CreateInputContext 报 UnknownObject",
         cause="主总线 org.fcitx.Fcitx5 上对象路径是 /org/freedesktop/portal/inputmethod；/inputmethod 只在 portal 总线 org.freedesktop.portal.Fcitx 上；接口 org.fcitx.Fcitx.InputMethod1/InputContext1",
         rule="主总线用 /org/freedesktop/portal/inputmethod；IC 方法 ProcessKeyEvent(uuubu)→b、FocusIn/Out、SetCursorRect(iiii)、SelectCandidate(i)；CommitString(s) 信号",
         src="dbusfrontend.cpp 5.1.21 源码 + ic-sim 实测",
         verify="addon-test a2"),
    dict(id="fc-uim-single-active-dispatch", cat="fcitx-api",
         title="InputPanel 只派发给唯一活跃 UI（ui_），非全体",
         symptom="Category=UI 注册成功（构造/update(StatusArea) 有日志）但打字组合永不到达 update(InputPanel)",
         cause="UserInterfaceManager::updateSingleComponent 只调 ui_ 单指针（非 uis_ 全表）；且 IC 带 ClientSideInputPanel 能力位时走 updateClientSideUIImpl 完全绕过 UI 插件",
         rule="测试环境 --disable=classicui,kimpanel 保证选中自己；keyboard-us 不产生组合——必须组内加 pinyin 并 SetCurrentIM（要求目标已在组列表，组名从总线取：'Default' 被 zh_CN locale 翻译）",
         src="uim.cpp/userinterfacemanager.cpp 5.1.21 源码；a7 排障（2026-08-26）",
         verify="addon-test a7"),
    dict(id="proto-json-dumps-space", cat="container-test",
         title="python json.dumps 默认冒号后带空格，紧凑解析器全盲",
         symptom="stdio 后端事件全部被静默忽略（子进程正常退出、管道数据在、C++ 侧零日志）",
         cause="json.dumps 默认 separators=(', ', ': ')，wire 上是 \"method\": \"asr/partial\"；C++ 扁平查找按 \"method\":\" 精确匹配落空——未知 method 按协议忽略=静默吞掉一切",
         rule="后端 emit 必须 separators=(\",\", \":\")；C++ 解析器 jsonValuePos 容忍冒号后空白（宽松在查找侧）；排查此类问题先看子进程退出码（wrapper 记 EXIT=$?），退出码 0 + 零事件=解析盲区非崩溃",
         src="a8 首跑失败三轮定位（2026-08-26 晚）",
         verify="addon-test a8"),
    dict(id="glib288-variant-traps", cat="container-test",
         title="glib 2.88 GVariant 三个坑（ic-sim 实证）",
         symptom="builder 判无效/参数空体/子项类型断言",
         cause="①g_variant_new(\"(a(ss))\", builder_end产物) 把传参当 builder 判无效；②builder 直建 (a(ss)) 元组时 add(\"(ss)\") 子项必须是完整 a(ss) 数组；③返回 (oay) 要用 (&o^ay) 解析",
         rule="数组参数用 g_variant_new_tuple(&array_variant, 1) 构造（无格式解析全绕开）；最小复现程序 /tmp/gvariant-repro*.c 三轮二分定位",
         src="ic-sim 开发（2026-08-26 晚）",
         verify="addon-test 6/6"),
    dict(id="bd-headless-popup-guard", cat="build-deploy",
         title="headless 环境 popup 分支必须判空 im_",
         symptom="无显示容器 fcitx5 会话即 SIGSEGV",
         cause="ensurePopup popup 分支裸调 zwp_input_method_v2_get_input_popup_surface(im_=null)",
         rule="else if (im_) 守卫 + 无处可挂仅记日志 return false——会话逻辑不受影响",
         src="addon-test 容器前置修复",
         verify="addon-test a2 全流程"),
    # ── 容器与测试 ───────────────────────────────────────────────────────
    dict(id="ct-scale-wildcard-winit", cat="container-test",
         title="嵌套 niri 输出名不吃 output \"*\" 通配",
         symptom="scale 配置静默不生效，全部轮次假跑 1.0",
         cause="winit 后端输出名（Smithay Winit Unknown）不匹配通配",
         rule="同时写 output \"Winit\" 规则；NIRI_TEST_SCALE 透传；验证 scale 生效要查 niri msg outputs",
         src="容器 scale 大坑定案",
         verify="双 scale 矩阵"),
    dict(id="ct-pkill-hits-container", cat="container-test",
         title="宿主 pkill 杀容器内同名进程",
         symptom="套件从某刻起全用例零信号式假失败",
         cause="rootless 容器进程同 UID 宿主可见；pkill -x fcitx5 波及容器",
         rule="动宿主 fcitx5 前 podman ps 查活跃套件；部署与测试互斥",
         src="19/37 假失败定案",
         verify="-"),
    dict(id="ct-skip-false-green", cat="container-test",
         title="守卫恒假→静默跳过→假绿",
         symptom="20/20 全绿但 4 个用例实际没跑",
         cause="sed 批量改动误伤 [ -x path ] 测试成四参数恒假",
         rule="结果核查必须含『跳过』检测；批量 sed 后 grep 改动行；跳过分支文案统一可扫描",
         src="timeout sed 事故",
         verify="结果审计脚本/人工"),
    dict(id="ct-wfrecorder-kill9", cat="container-test",
         title="1080p 下 wf-recorder 无视 SIGINT/SIGTERM",
         symptom="rec_stop 的 wait 永久挂起（套件卡死 40 分钟）",
         cause="高分辨率无损编码器不返回事件循环",
         rule="SIGINT 宽限→kill -9 兜底；编码参数 -p crf=30 -r 24 降负载",
         src="sway 1080p 首轮事故",
         verify="套件按时完成"),
    dict(id="ct-virtpoint-extent-normalization", cat="container-test",
         title="virtpoint 坐标经 extent 归一化（分辨率无关）",
         symptom="换分辨率后点击落点漂移",
         cause="motion_absolute 按 extent 归一",
         rule="用例坐标保持 extent 1280x720 语义（分数位置），物理分辨率变了也命中",
         src="1080p 迁移零改动验证",
         verify="1080p 套件全绿"),
    dict(id="ct-injectkey-vs-simulatekey", cat="container-test",
         title="SimulateKey 直喂状态机；InjectKey 走真实事件管线",
         symptom="用 SimulateKey 喂字母拼音引擎看不见",
         cause="TestService::SimulateKey 绕过 watcher/引擎",
         rule="验证拦截/透传语义、拼音组合必须 InjectKey",
         src="r25 坑",
         verify="c7/c8 拼音幕"),
    dict(id="ct-session-residue-swallows-trigger", cat="container-test",
         title="候选/录音残留吞下一用例触发键",
         symptom="后续用例首按无反应",
         cause="状态机『活动会话只认会话 IC』+残留 candidates",
         rule="每用例收尾 back_to_idle() 收敛循环（三次踩坑固化为公共函数）",
         src="r24/r34/r37 三连",
         verify="连续用例稳定"),
    dict(id="ct-headless-nested-screencopy", cat="container-test",
         title="嵌套 niri 的 screencopy 不出帧，录屏对宿主合成器",
         symptom="录屏黑屏/无帧",
         cause="嵌套 winit 后端不支持 screencopy",
         rule="grim/wf-recorder 全部指向 CAGE_SOCK（宿主 sway 的 wayland-N）",
         src="cage→sway 迁移保持",
         verify="截图非空"),
    dict(id="ct-pil-in-container-only", cat="container-test",
         title="niri 镜像内有 pillow；宿主无",
         symptom="宿主跑像素脚本失败",
         cause="镜像装了 python-pillow",
         rule="像素断言/标注在容器内跑；宿主只有 ffmpeg/vision",
         src="像素断言工作流",
         verify="-"),
    dict(id="ct-stdin-consumed-by-chain", cat="container-test",
         title="交互容器 stdin 会被调用链吞掉",
         symptom="管道喂脚本给 MODE=shell 的 bash 无输入",
         cause="su/dbus-run-session 链消耗 stdin",
         rule="探针脚本用文件挂载注入，不走 stdin",
         src="probe-r36 折腾记录",
         verify="-"),
    # ── 构建与部署 ───────────────────────────────────────────────────────
    dict(id="bd-local-lib-not-searched", cat="build-deploy",
         title="~/.local/lib 不入 addon 搜索路径",
         symptom="手工放的 .so 不被加载",
         cause="addon 搜索路径只有 /usr、/usr/local、~/.local/share 下特定结构",
         rule="部署一律走 pacman -U；验证装到位查 /proc/<pid>/maps",
         src="验证纪律",
         verify="maps grep aiinput"),
    dict(id="bd-deploy-verify-artifacts", cat="build-deploy",
         title="上机前验证产物：readelf/ldd -r/字符串",
         symptom="旧二进制仍在跑/漏符号上机崩",
         cause="乐观假设",
         rule="装后 grep -a 新日志串（中文串 strings 看不见）+ maps 核对；smoke 已加 ldd -r 拦截",
         src="验证纪律+崩机教训",
         verify="部署后检查单"),
    dict(id="bd-build-in-tmp", cat="build-deploy",
         title="容器内 /tmp 干净构建防时间戳跳过",
         symptom="改了代码 make 说无需重编",
         cause="挂载卷时间戳漂移致 cMake/make 跳过",
         rule="cmake -B /tmp/build；编译错误要确认 0 error（管道会吞退出码）",
         src="build.sh 结构+教训",
         verify="构建日志"),
    dict(id="bd-cage-headless-fixed-720p", cat="build-deploy",
         title="cage headless 输出 1280×720 硬编码",
         symptom="想要 1080p 无门",
         cause="cage 源码写死 headless 输出尺寸",
         rule="用 sway 托管（output HEADLESS-1 resolution 1920x1080）",
         src="1080p 迁移",
         verify="截图 1920×1080"),
    dict(id="bd-setcap-strip", cat="build-deploy",
         title="合成器二进制的 cap_sys_nice 需移除",
         symptom="rootless 容器里 sway/kwin exec EPERM",
         cause="包自带文件能力 rootless 无",
         rule="镜像构建时 setcap -r /usr/sbin/sway 等",
         src="Containerfile.host",
         verify="容器起得来"),
    dict(id="bd-journal-user-restarts", cat="build-deploy",
         title="用户会自行重启 fcitx5（终端启动无 journal）",
         symptom="对账时找不到测试期日志",
         cause="用户排障习惯+终端启动 stderr 不进 journal",
         rule="对账前先 pgrep 看 fcitx5 起始时间；日志缺失不等于没发生",
         src="多次对账经验",
         verify="-"),
    dict(id="bd-log-buffering-tail-caveat", cat="build-deploy",
         title="fcitx5 stderr 重定向到文件是块缓冲",
         symptom="journal/日志滞后，时间线推断被误导",
         cause="stdio 全缓冲",
         rule="以事件相对顺序+水位行号对账，勿信赖秒级时序；紧急时 SIGUSR?/重启冲刷",
         src="c7 卡死调查弯路",
         verify="-"),
]

CATS = ["wayland", "x11", "fcitx-api", "embedder", "app-behavior",
        "container-test", "build-deploy"]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    for it in ITEMS:
        body = f"""---
id: {it['id']}
category: {it['cat']}
title: {it['title']}
---

# {it['title']}

- **症状**：{it['symptom']}
- **根因**：{it['cause']}
- **约束规则**：{it['rule']}
- **来源**：{it['src']}
- **验证**：{it['verify']}
"""
        with open(os.path.join(here, it["id"] + ".md"), "w") as f:
            f.write(body)
    rows = "\n".join(
        f"- [{it['id']}]({it['id']}.md)（{it['cat']}）{it['title']}"
        for it in ITEMS
    )
    counts = {c: sum(1 for i in ITEMS if i["cat"] == c) for c in CATS}
    summary = " · ".join(f"{c} {counts[c]}" for c in CATS)
    index = f"""# 原子避坑知识资产 INDEX

共 {len(ITEMS)} 条（{summary}）。每条一文件：症状/根因/约束规则/来源/验证。
规则：重构动到的模块先过该类目清单；能固化为断言的进对应容器用例。
再生成：`python3 lab/knowledge/gen.py`（条目定义在脚本 ITEMS 内，加条目只改数据）。

## wayland
{chr(10).join(f'- [{i["id"]}]({i["id"]}.md) {i["title"]}' for i in ITEMS if i['cat']=='wayland')}

## x11 / satellite
{chr(10).join(f'- [{i["id"]}]({i["id"]}.md) {i["title"]}' for i in ITEMS if i['cat']=='x11')}

## fcitx5 API
{chr(10).join(f'- [{i["id"]}]({i["id"]}.md) {i["title"]}' for i in ITEMS if i['cat']=='fcitx-api')}

## flutter embedder
{chr(10).join(f'- [{i["id"]}]({i["id"]}.md) {i["title"]}' for i in ITEMS if i['cat']=='embedder')}

## 应用行为
{chr(10).join(f'- [{i["id"]}]({i["id"]}.md) {i["title"]}' for i in ITEMS if i['cat']=='app-behavior')}

## 容器与测试
{chr(10).join(f'- [{i["id"]}]({i["id"]}.md) {i["title"]}' for i in ITEMS if i['cat']=='container-test')}

## 构建与部署
{chr(10).join(f'- [{i["id"]}]({i["id"]}.md) {i["title"]}' for i in ITEMS if i['cat']=='build-deploy')}
"""
    with open(os.path.join(here, "INDEX.md"), "w") as f:
        f.write(index)
    print(f"生成 {len(ITEMS)} 条 + INDEX.md")


if __name__ == "__main__":
    main()
